services:
  postgres-dev:
    image: postgis/postgis:16-3.4

    container_name: smartfish-postgres-dev

    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}

    ports:
      - "5433:5432"

    tmpfs:
      - /var/lib/postgresql/data